name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Build
      run: |
        docker build --pull -t docker.pkg.github.com/kfox1111/u2f-sshd/u2f-sshd:latest -f Dockerfile .
    
    - name: Push
      run: |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/kfox1111/u2f-sshd/u2f-sshd:latest
